### ISSUE TITLE
[theme] add a series context bar

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-python-website#12]
@jstac had a great idea. It would be nice to have a context bar (below the current top menu bar) that shows users which lecture series they are reading and an easy way to navigate to another lecture set. 

Conversation from slack. 

```
Why don't we have a bar underneath the top level black bar on each subsite, such as https://python-advanced.quantecon.org/ (edited) 
This bar is like 1cm deep, goes all the way across, and is divided into 4.
It shows the words "Top", "Programming" "Introductory" and "Advanced"
The one that you are currently in is highlighted.
```

**Comment by DrDrij** [comment]
- Added the site nav bar
- Added QE logo squares in the header to replace "Go to QuantEcon"
- Search across sites seems to work well? (https://python.quantecon.org/search/?q=classical%20theorems)

https://python.quantecon.org/

**Comment by jstac** [comment]
Thanks @DrDrij !

Looks great.  Some small requests:

* The site nav bar is great but I think we should have it on the three sub-sites (programming, intro, advanced) rather than the top level site (python.quantecon.org).  Or we could have it on all 4, but I think that's excessive, since it's easy to navigate from the top-level site.  

* In the nav bar "Home" is good but for the other three, instead of "Programming" etc, could we please try the greek symbols?  

* Could we please change "About these lectures" to "About" in slightly larger font?

Just when you can spare a bit of time.  Thanks again.

**Comment by jstac** [comment]
Ok, so don't get mad because I'm going to change my mind :grimacing: 

Everying above, except the last point.  Instead of changing "About these lectures" to "About", please drop it altogether. 

Instead, please add a sentence of text immediately below the black header with the following:

"This project provides a series of online textbooks on Python programming and quantitative economic modeling, designed and written by Thomas J. Sargent and John Stachurski.  Read more..."  

Now "Read more" links to the about page.

Thanks :+1: :grimacing: :smiley:

**Comment by mmcky** [comment]
hey @DrDrij once there are PR's for the three lecture series `theme` repos. Can you add them here and I will then merge them and update the `build` server.

**Comment by DrDrij** [comment]
PRs have been created across the 3 py sites with the new site-bar nav.

![image](https://user-images.githubusercontent.com/5886045/78662145-40fec780-7913-11ea-96af-057f91437e1f.png)

Also @jstac I've updated the landing site: https://python.quantecon.org/

![image](https://user-images.githubusercontent.com/5886045/78662662-2c6eff00-7914-11ea-9ad3-c9dbd56de7f5.png)

**Comment by jstac** [comment]
Perfect!  Thanks @DrDrij !

**Comment by mmcky** [comment]
Closing as this is now completed
